host: itdog.de

analyticsService:
  image: dbayarchyk/itdog-analytics-service

authService:
  image: dbayarchyk/itdog-auth-service

commentService:
  image: dbayarchyk/itdog-comment-service

marketService:
  image: dbayarchyk/itdog-market-service

web:
  image: dbayarchyk/itdog-web
  env:
    SERVER_SIDE_API_URL: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local/api
    NEXT_PUBLIC_CLIENT_SIDE_API_URL: /api
