# !!! IMPORTANT !!!
# {{ RELEASE_TAG }} substring will be replaced automatically with a SHA1 in CI
# Do not remove it!

host: itdog.dbayarchyk.xyz

analyticsService:
  image: dbayarchyk/itdog-analytics-service:{{ RELEASE_TAG }}

authService:
  image: dbayarchyk/itdog-auth-service:{{ RELEASE_TAG }}

commentService:
  image: dbayarchyk/itdog-comment-service:{{ RELEASE_TAG }}

marketService:
  image: dbayarchyk/itdog-market-service:{{ RELEASE_TAG }}

web:
  image: dbayarchyk/itdog-web:{{ RELEASE_TAG }}
  env:
    SERVER_SIDE_API_URL: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local/api
    NEXT_PUBLIC_CLIENT_SIDE_API_URL: /api
