version: "3"
services:
  api-auth-service:
    build: ./api/services/auth/.
    depends_on:
      - postgres
    volumes:
      - ./api/services/auth:/usr/src/app
    environment:
      FLASK_ENV: development

  api-article-service:
    build: ./api/services/article/.
    depends_on:
      - postgres
    volumes:
      - ./api/services/article:/usr/src/app
    environment:
      FLASK_ENV: development

  api-comment-service:
    build: ./api/services/comment/.
    depends_on:
      - postgres
    volumes:
      - ./api/services/comment:/usr/src/app
    environment:
      FLASK_ENV: development

  api-gateway-service:
    build: ./api/services/gateway/.
    depends_on:
      - api-auth-service
      - api-article-service
      - api-comment-service
    volumes:
      - ./api/services/gateway:/usr/src/app
    environment:
      FLASK_ENV: development

  postgres:
    build: ./database/.
    volumes:
      # persist data even if container shuts down
      - ./database/data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: itdog_database

  postgres-pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

  client:
    build: ./client/.
    depends_on:
      - api-auth-service
      - api-article-service
    volumes:
      - ./client:/usr/src/app
    command: ["npm", "run", "dev"]

  admin:
    build: ./admin/.
    depends_on:
      - api-auth-service
      - api-article-service
    volumes:
      - ./admin:/usr/src/app
    command: ["npm", "run", "dev"]
    environment:
      BASE_URL: /admin

  nginx:
    restart: always
    build: ./nginx/.
    ports:
      - "4000:80"
    depends_on:
      - api-auth-service
      - api-article-service
      - client
      - admin
