version: "3"
services:
  api-services-auth:
    build: ./api/services/auth/.
    ports:
      - "5000:5000"
    volumes:
      - ./api/services/auth:/usr/src/app
    environment:
      FLASK_ENV: development

  api-services-article:
    build: ./api/services/article/.
    ports:
      - "5001:5000"
    volumes:
      - ./api/services/article:/usr/src/app
    environment:
      FLASK_ENV: development

  postgres:
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    volumes:
      # persist data even if container shuts down
      - ./database/data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: itdog_database

  postgres-pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

  client:
    build: ./client/.
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    command: ["npm", "run", "dev", "&&", "npm", "run", "watch:tailwind"]
