apiVersion: skaffold/v2beta10
kind: Config
deploy:
  helm:
    releases:
      - name: itdog
        artifactOverrides:
          analyticsService:
            image: dbayarchyk/itdog-analytics-service
          authService:
            image: dbayarchyk/itdog-auth-service
          commentService:
            image: dbayarchyk/itdog-comment-service
          emailService:
            image: dbayarchyk/itdog-email-service
          marketService:
            image: dbayarchyk/itdog-market-service
          web:
            image: dbayarchyk/itdog-web
        chartPath: ./infrastructure/helm
        valuesFiles:
          - ./infrastructure/helm/values/local.yaml
build:
  local:
    push: false
  artifacts:
    - image: dbayarchyk/itdog-web
      context: web
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.json"
            dest: .
          - src: "**/*.tsx?"
            dest: .
          - src: "styles/**/*"
            dest: .
    - image: dbayarchyk/itdog-comment-service
      context: api/services/comment
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: dbayarchyk/itdog-market-service
      context: api/services/market
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: dbayarchyk/itdog-auth-service
      context: api/services/auth
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: dbayarchyk/itdog-analytics-service
      context: api/services/analytics
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: dbayarchyk/itdog-email-service
      context: api/services/email
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
