const CITIES = [
  { id: "berlin", label: "Berlin" },
  { id: "münchen", label: "München" },
  { id: "hamburg", label: "Hamburg" },
  { id: "frankfurt am", label: "Frankfurt am" },
  { id: "main", label: "Main" },
  { id: "köln", label: "Köln" },
  { id: "leipzig", label: "Leipzig" },
  { id: "düsseldorf", label: "Düsseldorf" },
  { id: "nürnberg", label: "Nürnberg" },
  { id: "stuttgart", label: "Stuttgart" },
  { id: "dresden", label: "Dresden" },
  { id: "heidelberg", label: "Heidelberg" },
  { id: "bremen", label: "Bremen" },
  { id: "bonn", label: "Bonn" },
  { id: "regensburg", label: "Regensburg" },
  { id: "hannover", label: "Hannover" },
  { id: "essen", label: "Essen" },
  { id: "freiburg im", label: "Freiburg im" },
  { id: "breisgau", label: "Breisgau" },
  { id: "lübeck", label: "Lübeck" },
  { id: "dortmund", label: "Dortmund" },
  { id: "potsdam", label: "Potsdam" },
  { id: "erfurt", label: "Erfurt" },
  { id: "aachen", label: "Aachen" },
  { id: "trier", label: "Trier" },
  { id: "wiesbaden", label: "Wiesbaden" },
  { id: "koblenz", label: "Koblenz" },
  { id: "würzburg", label: "Würzburg" },
  { id: "augsburg", label: "Augsburg" },
  { id: "mainz", label: "Mainz" },
  { id: "mannheim", label: "Mannheim" },
  { id: "bamberg", label: "Bamberg" },
  { id: "duisburg", label: "Duisburg" },
  { id: "ulm", label: "Ulm" },
  { id: "weimar", label: "Weimar" },
  { id: "münster", label: "Münster" },
  { id: "bochum", label: "Bochum" },
  { id: "wolfsburg", label: "Wolfsburg" },
  { id: "gelsenkirchen", label: "Gelsenkirchen" },
  { id: "karlsruhe", label: "Karlsruhe" },
  { id: "schwerin", label: "Schwerin" },
  { id: "kiel", label: "Kiel" },
  { id: "rostock", label: "Rostock" },
  { id: "darmstadt", label: "Darmstadt" },
  { id: "bielefeld", label: "Bielefeld" },
  { id: "erlangen", label: "Erlangen" },
  { id: "wuppertal", label: "Wuppertal" },
  { id: "ingolstadt", label: "Ingolstadt" },
  { id: "paderborn", label: "Paderborn" },
  { id: "bremerhaven", label: "Bremerhaven" },
  { id: "magdeburg", label: "Magdeburg" },
  { id: "oldenburg", label: "Oldenburg" },
  { id: "chemnitz", label: "Chemnitz" },
];

export default CITIES;
