const POSITIONS = [
  { id: "technical writer", label: "Technical Writer" },
  { id: "software engineer", label: "Software Engineer" },
  { id: "qa engineer/ tester", label: "QA Engineer/ Tester" },
  { id: "project manager", label: "Project Manager" },
  { id: "senior software engineer", label: "Senior Software Engineer" },
  { id: "marketing manager (it)", label: "Marketing Manager (IT)" },
  { id: "junior software engineer", label: "Junior Software Engineer" },
  { id: "lead software engineer", label: "Lead Software Engineer" },
  { id: "senior qa engineer/ tester", label: "Senior QA Engineer/ Tester" },
  { id: "team leader", label: "Team Leader" },
  { id: "junior qa engineer/ tester", label: "Junior QA Engineer/ Tester" },
  { id: "html coder", label: "HTML Coder" },
  { id: "business analyst", label: "Business Analyst" },
  { id: "system administrator", label: "System Administrator" },
  { id: "senior project manager", label: "Senior Project Manager" },
  { id: "qa team leader", label: "QA Team Leader" },
  { id: "hr", label: "HR" },
  { id: "gui designer", label: "GUI Designer" },
  { id: "web designer", label: "Web Designer" },
  {
    id: "software maintenance engineer",
    label: "Software Maintenance Engineer",
  },
  { id: "seo specialist", label: "SEO Specialist" },
  { id: "copywriter", label: "Copywriter" },
  { id: "support engineer", label: "Support Engineer" },
  { id: "department manager", label: "Department Manager" },
  { id: "pr manager (it)", label: "PR Manager (IT)" },
  { id: "content manager", label: "Content Manager" },
  { id: "solution architect", label: "Solution Architect" },
  { id: "support specialist", label: "Support Specialist" },
  { id: "data analyst", label: "Data Analyst" },
  { id: "chief technical officer", label: "Chief Technical Officer" },
  { id: "data scientist", label: "Data Scientist" },
  { id: "qa automation engineer", label: "QA Automation Engineer" },
  { id: "devops engineer", label: "DevOps Engineer" },
  { id: "product manager", label: "Product Manager" },
  { id: "solution engineer", label: "Solution Engineer" },
  { id: "system analyst", label: "System Analyst" },
  { id: "solution engineer", label: "Solution Engineer" },
  { id: "support specialist", label: "Support Specialist" },
  { id: "3d artist", label: "3D Artist" },
  { id: "support engineer", label: "Support Engineer" },
  { id: "etl developer", label: "ETL Developer" },
  { id: "cto", label: "CTO" },
  { id: "performance analyst", label: "Performance Analyst" },
  { id: "content manager", label: "Content Manager" },
  { id: "data analyst", label: "Data Analyst" },
  { id: "solution architect", label: "Solution Architect" },
  { id: "sales manager", label: "Sales Manager" },
  { id: "data engineer", label: "Data Engineer" },
  { id: "data engineer", label: "Data Engineer" },
  { id: "recruiter", label: "Recruiter" },
  { id: "motion designer", label: "Motion Designer" },
  { id: "ua manager", label: "UA Manager" },
];

export default POSITIONS;
