apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market
  template:
    metadata:
      labels:
        app: market
    spec:
      containers:
        - name: market
          image: dbayarchyk/itdog-market-service
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: market-generic-secret
                  key: MONGODB_URL
