apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  selector:
    app: analytics
  type: ClusterIP
  ports:
    - name: analytics
      protocol: TCP
      port: 8000
      targetPort: 8000
