version: 2.1
orbs:
  node: circleci/node@4.0.0
  docker: circleci/docker@1.2.1
jobs:
  # --- START: Market service jobs: ---
  init-market-service:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./api/services/market
      - persist_to_workspace:
          root: ./api/services/market
          paths:
            - node_modules/*

  lint-market-service:
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: ./api/services/market
      - run: cd api/services/market && npm run lint

  test-market-service:
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: ./api/services/market
      - run: cd api/services/market && npm run test

  build-and-push-market-service-docker-image:
    machine: true
    steps:
      - checkout
      - run: docker build -t dbayarchyk/itdog-market-service -f ~/project/api/services/market/Dockerfile ~/project/api/services/market
      - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
      - run: docker push dbayarchyk/itdog-market-service
  # --- END: Market service jobs ---

  # --- START: Comment service jobs: ---
  init-comment-service:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./api/services/comment
      - persist_to_workspace:
          root: ./api/services/comment
          paths:
            - node_modules/*

  lint-comment-service:
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: ./api/services/comment
      - run: cd api/services/comment && npm run lint

  test-comment-service:
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: ./api/services/comment
      - run: cd api/services/comment && npm run test

  build-and-push-comment-service-docker-image:
    machine: true
    steps:
      - checkout
      - run: docker build -t dbayarchyk/itdog-comment-service -f ~/project/api/services/comment/Dockerfile ~/project/api/services/comment
      - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
      - run: docker push dbayarchyk/itdog-comment-service
  # --- END: Comment service jobs ---

  # --- START: Web jobs: ---
  init-web:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./web
      - persist_to_workspace:
          root: ./web
          paths:
            - node_modules/*

  lint-web:
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: ./web
      - run: cd web && npm run lint

  test-web:
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: ./web
      - run: cd web && npm run test

  build-and-push-web-docker-image:
    machine: true
    steps:
      - checkout
      - run: docker build -t dbayarchyk/itdog-web -f ~/project/web/Dockerfile ~/project/web
      - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
      - run: docker push dbayarchyk/itdog-web
  # --- END: Web jobs ---
workflows:
  build-and-publish-docker-images:
    jobs:
      - init-market-service
      - init-comment-service
      - init-web

      - lint-market-service:
          requires:
            - init-market-service
      - lint-comment-service:
          requires:
            - init-comment-service
      - lint-web:
          requires:
            - init-web

      - test-market-service:
          requires:
            - init-market-service
      - test-comment-service:
          requires:
            - init-comment-service
      - test-web:
          requires:
            - init-web

      - build-and-push-market-service-docker-image:
          requires:
            - lint-market-service
            - test-market-service
          filters:
            branches:
              only:
                - master
      - build-and-push-comment-service-docker-image:
          requires:
            - lint-comment-service
            - test-comment-service
          filters:
            branches:
              only:
                - master
      - build-and-push-web-docker-image:
          requires:
            - lint-web
            - test-web
          filters:
            branches:
              only:
                - master
