version: 2.1
orbs:
  docker: circleci/docker@1.2.1
workflows:
  build-and-publish-docker-images:
    jobs:
      - docker/publish:
          name: Publish api auth service docker image
          image: dbayarchyk/itdog-api-auth-service
          path: ~/project/api/services/auth
          dockerfile: Dockerfile
          docker-context: ~/project/api/services/auth
          filters:
            branches:
              only:
                - master
      - docker/publish:
          name: Publish api article service docker image
          image: dbayarchyk/itdog-api-article-service
          path: ~/project/api/services/article
          dockerfile: Dockerfile
          docker-context: ~/project/api/services/article
          filters:
            branches:
              only:
                - master
      - docker/publish:
          name: Publish api comment service docker image
          image: dbayarchyk/itdog-api-comment-service
          path: ~/project/api/services/comment
          dockerfile: Dockerfile
          docker-context: ~/project/api/services/comment
          filters:
            branches:
              only:
                - master
      - docker/publish:
        name: Publish api market service docker image
        image: dbayarchyk/itdog-api-market-service
        path: ~/project/api/services/market
        dockerfile: Dockerfile
        docker-context: ~/project/api/services/market
        filters:
          branches:
            only:
              - master
      - docker/publish:
          name: Publish api gateway service docker image
          image: dbayarchyk/itdog-api-gateway-service
          path: ~/project/api/services/gateway
          dockerfile: Dockerfile
          docker-context: ~/project/api/services/gateway
          filters:
            branches:
              only:
                - master
      - docker/publish:
          name: Publish admin docker image
          image: dbayarchyk/itdog-admin
          path: ~/project/admin
          dockerfile: Dockerfile
          docker-context: ~/project/admin
          filters:
            branches:
              only:
                - master
      - docker/publish:
          name: Publish client docker image
          image: dbayarchyk/itdog-client
          path: ~/project/client
          dockerfile: Dockerfile
          docker-context: ~/project/client
          filters:
            branches:
              only:
                - master
