apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      labels:
        app: comment
    spec:
      containers:
        - name: comment
          image: {{ .Values.commentService.image }}
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: comment-generic-secret
                  key: MONGODB_URL
