apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
        - name: analytics
          image: {{ .Values.analyticsService.image }}
          env:
            - name: GOOGLE_ANALYTICS_VIEW_ID
              value: "234204206"
            - name: GOOGLE_SERVICE_ACCOUNT_CLIENT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: analytics-generic-secret
                  key: GOOGLE_SERVICE_ACCOUNT_CLIENT_EMAIL
            - name: GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: analytics-generic-secret
                  key: GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY
