apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: dbayarchyk/itdog-auth-service
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: auth-generic-secret
                  key: MONGODB_URL
