apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: {{ .Values.authService.image }}
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: auth-generic-secret
                  key: MONGODB_URL
            - name: ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-generic-secret
                  key: ACCESS_TOKEN_SECRET
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-generic-secret
                  key: REFRESH_TOKEN_SECRET
