name: Continuous Integration

on:
  push:
    branches-ignore:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout master
        # By default github downloads only the current branch. We also want to have master
        # branch locally to be able to run test only for the files that have been changed since master. 
        # https://dev.to/bnb/jest-and-the-changedsince-flag-in-github-actions-ci-468i
        run: |
          git fetch --no-tags --depth=1 origin master
          git checkout -b master
          git checkout ${{ github.event.pull_request.head.sha }}
      - name: Cache and restore dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Bootstrap all packages
        run: npm run bootstrap
      - name: Lint all packages
        run: npm run lint
      - name: Test all packages
        env:
          CI: true
        run: npm run test:ci