name: Remove the preview environment

on:
  delete:
    branches-ignore:
      - "master"

jobs:
  remove-preview-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save news-portal
      - name: Uninstall the preview helm release
        run: |
          BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)
          SANITIZED_BRANCH=${BRANCH//[^a-zA-Z0-9-_]/-}
          DOMAIN_RECORD_NAME=${SANITIZED_BRANCH}.itdog

          helm uninstall ${DOMAIN_RECORD_NAME} infrastructure/helm --namespace=${SANITIZED_BRANCH} 
      - name: Remove the preview namespace
        run: |
          BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)
          SANITIZED_BRANCH=${BRANCH//[^a-zA-Z0-9-_]/-}

          kubectl delete namespace ${SANITIZED_BRANCH}
      - name: Remove the preview DNS record
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
        run: |
          BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)
          SANITIZED_BRANCH=${BRANCH//[^a-zA-Z0-9-_]/-}
          PREVIEW_DNS_RECORD_ID=$(doctl compute domain records list ${DOMAIN} --format ID,Name --no-header | grep ${SANITIZED_BRANCH} | awk '{print $1;}')

          doctl compute domain records delete ${DOMAIN} ${PREVIEW_DNS_RECORD_ID}